name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pack-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack
      run: dotnet pack ./src/ConsoleApp -p:PackageVersion=1.0.$GITHUB_RUN_NUMBER
    # login to nuget github package registry
    - name: NuGet Authenticate
      run: dotnet nuget add source https://nuget.pkg.github.com/molnarbence/index.json --name github --username molnarbence --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    # push the package to the github package registry
    - name: Push
      run: dotnet nuget push ./src/ConsoleApp/packages/UpdateDns.1.0.$GITHUB_RUN_NUMBER.nupkg --source github


      
